FileAppMvc/Models/ErrorViewModel.cs
namespace FileAppMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FileAppMvc/Models/FileViewModel.cs
namespace FileAppMvc.Models
{
    public class FileViewModel
    {
        public string FileName { get; set; } = "";
    }
}

FileAppMvc/Controllers/FileServiceController.cs
using FileAppMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace FileAppMvc.Controllers
{
    
    
    [RequestSizeLimit(150 * 1024 * 1024)]       //unit is bytes => 150Mb
    [RequestFormLimits(MultipartBodyLengthLimit = 150 * 1024 * 1024)]
    public class FileServiceController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly string _fileDirectoryName = "Files";

        public FileServiceController(IWebHostEnvironment env)
        {
            _env = env;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FileUpload()
        {
            return View();
        }
        public IActionResult FileDownload()
        {
            string serverDirectory = Path.Combine(_env.WebRootPath, _fileDirectoryName);
            string[] filePaths = Directory.GetFiles(serverDirectory);

            List<FileViewModel> fileList = new List<FileViewModel>();
            foreach (string filepath in filePaths)
            {
                fileList.Add(new FileViewModel { FileName = Path.GetFileName(filepath) });
            }
            return View(fileList);
        }


        public FileResult Downloadfile(string fileName)
        {
            var filePath = Path.Combine(_env.WebRootPath, _fileDirectoryName, fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(filePath);

            return File(bytes, "application/octet-stream", fileName);
        }


        [HttpPost]
        public async Task<IActionResult> ActionFileUpload(IFormFile file)
        {
            if (file == null) 
                TempData["msg"] = "File Upload fail ( null )";
            else
            {
                bool rtn = await UploadFile(file);
                if (rtn) TempData["msg"] = "File Uploaded sccessfully";
                else TempData["msg"] = "File Upload fail";

            }

            return View("FileUpload");

        }

        public async Task<bool> UploadFile(IFormFile file)
        {
            bool isCopied = false;
            try
            {
                if (file.Length > 0)
                {
                    //var filePath = Path.Combine(_env.ContentRootPath, "UploadFiles", file.FileName);
                    var filePath = Path.Combine(_env.WebRootPath, _fileDirectoryName, file.FileName);

                    // 파일이 있어면 새로 생성함
                    using var fileStream = new FileStream(filePath, FileMode.Create);
                    await file.CopyToAsync(fileStream);

                    isCopied = true;
                }
                else
                    isCopied = false;
            }
            catch (Exception)
            {
                throw;
            }
            return isCopied;
        }

    }
}

FileAppMvc/Controllers/HomeController.cs
using FileAppMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FileAppMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IWebHostEnvironment _env;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment env)
        {
            _logger = logger;
            _env = env;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FileAppMvc/Views/FileService/FileDownload.cshtml
@using FileAppMvc.Models
@model List<FileViewModel>

@{
    ViewData["Title"] = "File download";
}

<html>
    <head>
       <meta name="viewport" content="width=device-width" />
       <title>File Download </title>

    </head>
    <body>
        <div class="text-center">
            <h1 class="display-4">File Download</h1>
        </div>
        <div class="table-responsive">
            <table class="table table-responsive table-bordered">
                <tr>
                    <th>File Name</th>
                    <th></th>
                </tr>
                @foreach(FileViewModel file in Model)
                {
                    <tr>
                        <td>@file.FileName</td>
                        <td> <a href="/FileService/Downloadfile?fileName=@file.FileName" >Download</a></td>
                        @*<td>@Html.ActionLink("listfiles","downloadfile", new {fileName=file.FileName})</td>*@
                        
                    </tr>
                }
            </table>
        </div>

    </body>

</html>

FileAppMvc/Views/FileService/FileUpload.cshtml
@{
    ViewData["Title"] = "File Upload";
}

<div class="text-center">
    <h1 class="display-4">File Upload</h1>
</div>

<div class="container">
    <div class="mb-3 mt-3">
        <form method="post" enctype="multipart/form-data"
              asp-controller="FileService" 
              asp-action="ActionFileUpload" >
            <div class="mb-3 col-md-10">
                <label class="form-label">Upload File</label>
                <input type="file" name="file" class="form-control"/>
            </div>
            <div class="mb-3">
                <input type="submit" value="Upload" class="btn btn-primary"/>
            </div>
            <div class="form-group">
                <span>@TempData["msg"]</span>
            </div>
        </form>
    </div>
</div>



@*
<h1>File Upload</h1>

<form method="post" enctype="multipart/form-data" 
    asp-controller="FileService" 
    asp-action="ActionFileUpload">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload File</p>
            <input type="file" name="file" />
        </div>
    </div>
    <div class="form-group">
        <input type = "submit" value="Upload file" />
    </div>
    <div class="form-group">
        <span>@TempData["msg"]</span>
    </div>
</form>*@

FileAppMvc/Views/FileService/Index.cshtml
@{
    ViewData["Title"] = "Welcome to file service";
}

<div>
    <a href="/FileService/FileUpload" >Go to File Upload</a> <br />
    <a href="/FileService/FileDownload" >Go to File Download</a>
</div>



@*<form method="post" enctype="multipart/form-data" 
    asp-controller="FileUpload" 
    asp-action="FileUpload">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload File</p>
            <input type="file" name="file" />
        </div>
    </div>
    <div class="form-group">
        <input type = "submit" value="Upload file" />
    </div>
    <div class="form-group">
        <span>@TempData["msg"]</span>
    </div>
</form>*@

FileAppMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a href="/FileService/FileUpload">Go to File Upload</a> <br />
    <br />
    <a href="/FileService/FileDownload">Go to File Download</a>
    
    <br/>
    <br />
    <br />

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FileAppMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FileAppMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileAppMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bbs App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FileAppMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>